site_name: mqtt
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: ponylang
    primary: brown
    accent: amber
  features:
    - navigation.top
extra_css:
  - assets/ponylang.css
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_anchors: "L"
      use_pygments: true
  - pymdownx.superfences
  - toc:
      permalink: true
      toc_depth: 3
nav:
- mqtt: index.md
- package mqtt:
  - Package: "mqtt--index.md"
  - actor Main: "mqtt-Main.md"
- package mqtt/assembler:
  - Package: "mqtt-assembler--index.md"
  - actor Assembler: "mqtt-assembler-Assembler.md"
  - type Stream: "mqtt-assembler-Stream.md"
- package mqtt/configurator:
  - Package: "mqtt-configurator--index.md"
  - primitive ConfigFile: "mqtt-configurator-ConfigFile.md"
  - primitive DefaultBroker: "mqtt-configurator-DefaultBroker.md"
  - primitive FullConfigParams: "mqtt-configurator-FullConfigParams.md"
  - primitive IniAddress: "mqtt-configurator-IniAddress.md"
  - primitive IniCleansession: "mqtt-configurator-IniCleansession.md"
  - primitive IniId: "mqtt-configurator-IniId.md"
  - primitive IniKeepalive: "mqtt-configurator-IniKeepalive.md"
  - primitive IniMessage: "mqtt-configurator-IniMessage.md"
  - primitive IniName: "mqtt-configurator-IniName.md"
  - primitive IniPassword: "mqtt-configurator-IniPassword.md"
  - primitive IniPort: "mqtt-configurator-IniPort.md"
  - primitive IniQos: "mqtt-configurator-IniQos.md"
  - class IniReader: "mqtt-configurator-IniReader.md"
  - primitive IniSectionBroker: "mqtt-configurator-IniSectionBroker.md"
  - primitive IniSectionClient: "mqtt-configurator-IniSectionClient.md"
  - primitive IniSectionCredentials: "mqtt-configurator-IniSectionCredentials.md"
  - primitive IniSectionSubscriptions: "mqtt-configurator-IniSectionSubscriptions.md"
  - primitive IniSectionWill: "mqtt-configurator-IniSectionWill.md"
  - primitive IniTopic: "mqtt-configurator-IniTopic.md"
  - primitive IsValidQos: "mqtt-configurator-IsValidQos.md"
  - primitive MinConfigParams: "mqtt-configurator-MinConfigParams.md"
  - class MqttConfig: "mqtt-configurator-MqttConfig.md"
  - primitive QosPrefix: "mqtt-configurator-QosPrefix.md"
  - primitive SupportedQos: "mqtt-configurator-SupportedQos.md"
- package mqtt/connector:
  - Package: "mqtt-connector--index.md"
  - primitive ConnAckAccepted: "mqtt-connector-ConnAckAccepted.md"
  - class ConnAckPacket: "mqtt-connector-ConnAckPacket.md"
  - primitive ConnAckRefusedBadUserNameOrPassword: "mqtt-connector-ConnAckRefusedBadUserNameOrPassword.md"
  - primitive ConnAckRefusedIdentifierRejected: "mqtt-connector-ConnAckRefusedIdentifierRejected.md"
  - primitive ConnAckRefusedNotAuthorised: "mqtt-connector-ConnAckRefusedNotAuthorised.md"
  - primitive ConnAckRefusedProtocolVersion: "mqtt-connector-ConnAckRefusedProtocolVersion.md"
  - primitive ConnAckRefusedServerUnavailable: "mqtt-connector-ConnAckRefusedServerUnavailable.md"
  - type ConnAckReturnCode: "mqtt-connector-ConnAckReturnCode.md"
  - primitive ConnectClean: "mqtt-connector-ConnectClean.md"
  - type ConnectFlags: "mqtt-connector-ConnectFlags.md"
  - class ConnectPacket: "mqtt-connector-ConnectPacket.md"
  - primitive ConnectPassword: "mqtt-connector-ConnectPassword.md"
  - primitive ConnectQMask: "mqtt-connector-ConnectQMask.md"
  - primitive ConnectUserName: "mqtt-connector-ConnectUserName.md"
  - primitive ConnectWQos0: "mqtt-connector-ConnectWQos0.md"
  - primitive ConnectWQos1: "mqtt-connector-ConnectWQos1.md"
  - primitive ConnectWQos2: "mqtt-connector-ConnectWQos2.md"
  - primitive ConnectWRetain: "mqtt-connector-ConnectWRetain.md"
  - primitive ConnectWill: "mqtt-connector-ConnectWill.md"
  - actor Connector: "mqtt-connector-Connector.md"
  - primitive DefaultConnectFlags: "mqtt-connector-DefaultConnectFlags.md"
  - class DisconnectPacket: "mqtt-connector-DisconnectPacket.md"
  - primitive RejectionCode: "mqtt-connector-RejectionCode.md"
  - primitive RestoreConnectFlags: "mqtt-connector-RestoreConnectFlags.md"
- package mqtt/idIssuer:
  - Package: "mqtt-idIssuer--index.md"
  - class IdIssuer: "mqtt-idIssuer-IdIssuer.md"
- package mqtt/mqtt:
  - Package: "mqtt-mqtt--index.md"
  - actor Mqtt: "mqtt-mqtt-Mqtt.md"
  - trait MqttApplication: "mqtt-mqtt-MqttApplication.md"
  - trait MqttService: "mqtt-mqtt-MqttService.md"
- package mqtt/network:
  - Package: "mqtt-network--index.md"
  - class Client: "mqtt-network-Client.md"
  - actor OsNetwork: "mqtt-network-OsNetwork.md"
- package mqtt/pinger:
  - Package: "mqtt-pinger--index.md"
  - class Ping: "mqtt-pinger-Ping.md"
  - class PingReqPacket: "mqtt-pinger-PingReqPacket.md"
  - actor Pinger: "mqtt-pinger-Pinger.md"
- package mqtt/primitives:
  - Package: "mqtt-primitives--index.md"
  - type ArrayVal: "mqtt-primitives-ArrayVal.md"
  - primitive BrokerDisconnect: "mqtt-primitives-BrokerDisconnect.md"
  - primitive CPFlags: "mqtt-primitives-CPFlags.md"
  - type CPNoFlags: "mqtt-primitives-CPNoFlags.md"
  - type CPWithFlags: "mqtt-primitives-CPWithFlags.md"
  - primitive CleanSessionRequired: "mqtt-primitives-CleanSessionRequired.md"
  - primitive Clear: "mqtt-primitives-Clear.md"
  - type Command: "mqtt-primitives-Command.md"
  - primitive Commands: "mqtt-primitives-Commands.md"
  - primitive ConfigurationError: "mqtt-primitives-ConfigurationError.md"
  - primitive Connect: "mqtt-primitives-Connect.md"
  - primitive ConnectionClosed: "mqtt-primitives-ConnectionClosed.md"
  - primitive ConnectionRefused: "mqtt-primitives-ConnectionRefused.md"
  - type ControlArrayVal: "mqtt-primitives-ControlArrayVal.md"
  - primitive ControlConnAck: "mqtt-primitives-ControlConnAck.md"
  - primitive ControlConnect: "mqtt-primitives-ControlConnect.md"
  - primitive ControlDisconnect: "mqtt-primitives-ControlDisconnect.md"
  - primitive ControlPingReq: "mqtt-primitives-ControlPingReq.md"
  - primitive ControlPingResp: "mqtt-primitives-ControlPingResp.md"
  - primitive ControlPubAck: "mqtt-primitives-ControlPubAck.md"
  - primitive ControlPubComp: "mqtt-primitives-ControlPubComp.md"
  - primitive ControlPubRec: "mqtt-primitives-ControlPubRec.md"
  - primitive ControlPubRel: "mqtt-primitives-ControlPubRel.md"
  - primitive ControlPublish: "mqtt-primitives-ControlPublish.md"
  - primitive ControlSubAck: "mqtt-primitives-ControlSubAck.md"
  - primitive ControlSubscribe: "mqtt-primitives-ControlSubscribe.md"
  - primitive ControlUnsubAck: "mqtt-primitives-ControlUnsubAck.md"
  - primitive ControlUnsubscribe: "mqtt-primitives-ControlUnsubscribe.md"
  - primitive DecodeErr: "mqtt-primitives-DecodeErr.md"
  - primitive Discon: "mqtt-primitives-Discon.md"
  - type ErrorCode: "mqtt-primitives-ErrorCode.md"
  - primitive ForbiddenCode: "mqtt-primitives-ForbiddenCode.md"
  - primitive ForbiddenFlags: "mqtt-primitives-ForbiddenFlags.md"
  - primitive ForbiddenQos: "mqtt-primitives-ForbiddenQos.md"
  - primitive ForbiddenType: "mqtt-primitives-ForbiddenType.md"
  - primitive ForbiddenWillQos: "mqtt-primitives-ForbiddenWillQos.md"
  - type IdType: "mqtt-primitives-IdType.md"
  - primitive InvalidControl: "mqtt-primitives-InvalidControl.md"
  - primitive InvalidFlags: "mqtt-primitives-InvalidFlags.md"
  - primitive InvalidRemainingLength: "mqtt-primitives-InvalidRemainingLength.md"
  - primitive InvalidType: "mqtt-primitives-InvalidType.md"
  - primitive KeyDisplay: "mqtt-primitives-KeyDisplay.md"
  - primitive KeyIssuer: "mqtt-primitives-KeyIssuer.md"
  - primitive KeyNetwork: "mqtt-primitives-KeyNetwork.md"
  - primitive KeyPerf: "mqtt-primitives-KeyPerf.md"
  - primitive KeyPersistor: "mqtt-primitives-KeyPersistor.md"
  - primitive KeyPinger: "mqtt-primitives-KeyPinger.md"
  - primitive KeyRouter: "mqtt-primitives-KeyRouter.md"
  - primitive KeySpawner: "mqtt-primitives-KeySpawner.md"
  - primitive KeyTicker: "mqtt-primitives-KeyTicker.md"
  - primitive LoadTest: "mqtt-primitives-LoadTest.md"
  - type MQTTPublishFlags: "mqtt-primitives-MQTTPublishFlags.md"
  - primitive MalformedRequest: "mqtt-primitives-MalformedRequest.md"
  - primitive MalformedResponse: "mqtt-primitives-MalformedResponse.md"
  - trait MqActor: "mqtt-primitives-MqActor.md"
  - primitive Mute: "mqtt-primitives-Mute.md"
  - primitive NoError: "mqtt-primitives-NoError.md"
  - primitive NotConnected: "mqtt-primitives-NotConnected.md"
  - primitive NotImplemented: "mqtt-primitives-NotImplemented.md"
  - trait Packet: "mqtt-primitives-Packet.md"
  - type PacketIdentifierType: "mqtt-primitives-PacketIdentifierType.md"
  - type PacketNoIdentifierType: "mqtt-primitives-PacketNoIdentifierType.md"
  - type PacketWithTopicType: "mqtt-primitives-PacketWithTopicType.md"
  - class PublishArgs: "mqtt-primitives-PublishArgs.md"
  - primitive PublishDUP: "mqtt-primitives-PublishDUP.md"
  - primitive PublishQos0: "mqtt-primitives-PublishQos0.md"
  - primitive PublishQos1: "mqtt-primitives-PublishQos1.md"
  - primitive PublishQos2: "mqtt-primitives-PublishQos2.md"
  - primitive PublishRetain: "mqtt-primitives-PublishRetain.md"
  - type Qos: "mqtt-primitives-Qos.md"
  - primitive Qos0: "mqtt-primitives-Qos0.md"
  - primitive Qos1: "mqtt-primitives-Qos1.md"
  - primitive Qos2: "mqtt-primitives-Qos2.md"
  - primitive Quit: "mqtt-primitives-Quit.md"
  - primitive ReconnectFailed: "mqtt-primitives-ReconnectFailed.md"
  - primitive Service: "mqtt-primitives-Service.md"
  - primitive SocketError: "mqtt-primitives-SocketError.md"
  - primitive Sub: "mqtt-primitives-Sub.md"
  - type SubControl: "mqtt-primitives-SubControl.md"
  - primitive SubscribeFailed: "mqtt-primitives-SubscribeFailed.md"
  - primitive SubscribeStats: "mqtt-primitives-SubscribeStats.md"
  - primitive SubscribeTest: "mqtt-primitives-SubscribeTest.md"
  - primitive TestInterval: "mqtt-primitives-TestInterval.md"
  - primitive TestLength: "mqtt-primitives-TestLength.md"
  - primitive TestPrefix: "mqtt-primitives-TestPrefix.md"
  - primitive TestTopic: "mqtt-primitives-TestTopic.md"
  - primitive UnSub: "mqtt-primitives-UnSub.md"
  - primitive UnSubscribe: "mqtt-primitives-UnSubscribe.md"
  - primitive UnknownError: "mqtt-primitives-UnknownError.md"
- package mqtt/publisher:
  - Package: "mqtt-publisher--index.md"
  - primitive FlagsToQos: "mqtt-publisher-FlagsToQos.md"
  - primitive IsDup: "mqtt-publisher-IsDup.md"
  - primitive IsRetain: "mqtt-publisher-IsRetain.md"
  - class PubAckPacket: "mqtt-publisher-PubAckPacket.md"
  - class PubCompPacket: "mqtt-publisher-PubCompPacket.md"
  - class PubRecPacket: "mqtt-publisher-PubRecPacket.md"
  - class PubRelPacket: "mqtt-publisher-PubRelPacket.md"
  - class PublishPacket: "mqtt-publisher-PublishPacket.md"
  - actor Publisher: "mqtt-publisher-Publisher.md"
  - primitive QosToFlags: "mqtt-publisher-QosToFlags.md"
- package mqtt/router:
  - Package: "mqtt-router--index.md"
  - actor Router: "mqtt-router-Router.md"
- package mqtt/services:
  - Package: "mqtt-services--index.md"
  - actor Rtt: "mqtt-services-Rtt.md"
- package mqtt/subscriber:
  - Package: "mqtt-subscriber--index.md"
  - primitive SubAckFailure: "mqtt-subscriber-SubAckFailure.md"
  - class SubAckPacket: "mqtt-subscriber-SubAckPacket.md"
  - primitive SubAckSuccessMaxQos0: "mqtt-subscriber-SubAckSuccessMaxQos0.md"
  - primitive SubAckSuccessMaxQos1: "mqtt-subscriber-SubAckSuccessMaxQos1.md"
  - primitive SubAckSuccessMaxQos2: "mqtt-subscriber-SubAckSuccessMaxQos2.md"
  - type SubackReturnCode: "mqtt-subscriber-SubackReturnCode.md"
  - class SubscribePacket: "mqtt-subscriber-SubscribePacket.md"
  - actor Subscriber: "mqtt-subscriber-Subscriber.md"
  - class UnsubscribePacket: "mqtt-subscriber-UnsubscribePacket.md"
- package mqtt/terminal:
  - Package: "mqtt-terminal--index.md"
  - type Areas: "mqtt-terminal-Areas.md"
  - class BoxLine: "mqtt-terminal-BoxLine.md"
  - primitive CMD: "mqtt-terminal-CMD.md"
  - actor Display: "mqtt-terminal-Display.md"
  - primitive DisplayColour: "mqtt-terminal-DisplayColour.md"
  - primitive FRM: "mqtt-terminal-FRM.md"
  - class Handler: "mqtt-terminal-Handler.md"
  - primitive HighlightPeriod: "mqtt-terminal-HighlightPeriod.md"
  - class KbdInput: "mqtt-terminal-KbdInput.md"
  - primitive MSG: "mqtt-terminal-MSG.md"
  - actor Main: "mqtt-terminal-Main.md"
  - primitive STS: "mqtt-terminal-STS.md"
  - class StatusLine: "mqtt-terminal-StatusLine.md"
  - actor Terminal: "mqtt-terminal-Terminal.md"
  - actor UIManager: "mqtt-terminal-UIManager.md"
  - class UiNotify: "mqtt-terminal-UiNotify.md"
- package mqtt/utilities:
  - Package: "mqtt-utilities--index.md"
  - class BasePacket: "mqtt-utilities-BasePacket.md"
  - primitive BytesToU16: "mqtt-utilities-BytesToU16.md"
  - primitive BytesToValue: "mqtt-utilities-BytesToValue.md"
  - primitive DateString: "mqtt-utilities-DateString.md"
  - primitive Dump: "mqtt-utilities-Dump.md"
  - primitive DumpBin: "mqtt-utilities-DumpBin.md"
  - class FixedHeader: "mqtt-utilities-FixedHeader.md"
  - primitive FixedHeaderLength: "mqtt-utilities-FixedHeaderLength.md"
  - primitive FmtBin: "mqtt-utilities-FmtBin.md"
  - primitive FmtDec: "mqtt-utilities-FmtDec.md"
  - primitive FmtHex: "mqtt-utilities-FmtHex.md"
  - primitive GoodPkt1: "mqtt-utilities-GoodPkt1.md"
  - primitive GoodPkt2: "mqtt-utilities-GoodPkt2.md"
  - primitive GoodPkt3: "mqtt-utilities-GoodPkt3.md"
  - primitive GoodPkt4: "mqtt-utilities-GoodPkt4.md"
  - primitive GoodPkt5: "mqtt-utilities-GoodPkt5.md"
  - primitive GoodPkt6: "mqtt-utilities-GoodPkt6.md"
  - primitive IsFixedHeader: "mqtt-utilities-IsFixedHeader.md"
  - primitive MqString: "mqtt-utilities-MqString.md"
  - class MqTime: "mqtt-utilities-MqTime.md"
  - primitive RlByteCount: "mqtt-utilities-RlByteCount.md"
  - primitive Split: "mqtt-utilities-Split.md"
  - primitive ToQos: "mqtt-utilities-ToQos.md"
  - primitive ToQosBits: "mqtt-utilities-ToQosBits.md"
  - primitive TotalLength: "mqtt-utilities-TotalLength.md"
  - primitive U16ToBytes: "mqtt-utilities-U16ToBytes.md"
  - primitive U8ToQos: "mqtt-utilities-U8ToQos.md"
  - primitive ValueToRLBytes: "mqtt-utilities-ValueToRLBytes.md"
- source:
  - main.pony : "src/mqtt/main.md" 
  - assembler.pony : "src/mqtt-assembler/assembler.md" 
  - tests.pony : "src/mqtt-assembler/tests.md" 
  - iniStrings.pony : "src/mqtt-configurator/iniStrings.md" 
  - mqttConfig.pony : "src/mqtt-configurator/mqttConfig.md" 
  - ConnAckCodes.pony : "src/mqtt-connector/ConnAckCodes.md" 
  - conAckPacket.pony : "src/mqtt-connector/conAckPacket.md" 
  - connectCodes.pony : "src/mqtt-connector/connectCodes.md" 
  - connectPacket.pony : "src/mqtt-connector/connectPacket.md" 
  - connector.pony : "src/mqtt-connector/connector.md" 
  - disconnectPacket.pony : "src/mqtt-connector/disconnectPacket.md" 
  - idIssuer.pony : "src/mqtt-idIssuer/idIssuer.md" 
  - mqtt.pony : "src/mqtt-mqtt/mqtt.md" 
  - client.pony : "src/mqtt-network/client.md" 
  - osNetwork.pony : "src/mqtt-network/osNetwork.md" 
  - pinger.pony : "src/mqtt-pinger/pinger.md" 
  - pingReqPacket.pony : "src/mqtt-pinger/pingReqPacket.md" 
  - typeDefs.pony : "src/mqtt-primitives/typeDefs.md" 
  - errorCodes.pony : "src/mqtt-primitives/errorCodes.md" 
  - controlBytes.pony : "src/mqtt-primitives/controlBytes.md" 
  - commands.pony : "src/mqtt-primitives/commands.md" 
  - regStrings.pony : "src/mqtt-primitives/regStrings.md" 
  - pubFlags.pony : "src/mqtt-primitives/pubFlags.md" 
  - publishArgs.pony : "src/mqtt-primitives/publishArgs.md" 
  - flagFunctions.pony : "src/mqtt-publisher/flagFunctions.md" 
  - pubAckPacket.pony : "src/mqtt-publisher/pubAckPacket.md" 
  - pubCompPacket.pony : "src/mqtt-publisher/pubCompPacket.md" 
  - pubRecPacket.pony : "src/mqtt-publisher/pubRecPacket.md" 
  - pubRelPacket.pony : "src/mqtt-publisher/pubRelPacket.md" 
  - publishPacket.pony : "src/mqtt-publisher/publishPacket.md" 
  - publisher.pony : "src/mqtt-publisher/publisher.md" 
  - router.pony : "src/mqtt-router/router.md" 
  - rtt.pony : "src/mqtt-services/rtt.md" 
  - subAckCodes.pony : "src/mqtt-subscriber/subAckCodes.md" 
  - subAckPacket.pony : "src/mqtt-subscriber/subAckPacket.md" 
  - subscribePacket.pony : "src/mqtt-subscriber/subscribePacket.md" 
  - subscriber.pony : "src/mqtt-subscriber/subscriber.md" 
  - unsubscribePacket.pony : "src/mqtt-subscriber/unsubscribePacket.md" 
  - display.pony : "src/mqtt-terminal/display.md" 
  - colours.pony : "src/mqtt-terminal/colours.md" 
  - handler.pony : "src/mqtt-terminal/handler.md" 
  - main.pony : "src/mqtt-terminal/main.md" 
  - terminal.pony : "src/mqtt-terminal/terminal.md" 
  - uistamper.pony : "src/mqtt-terminal/uistamper.md" 
  - basePacket.pony : "src/mqtt-utilities/basePacket.md" 
  - functions.pony : "src/mqtt-utilities/functions.md" 
  - timestamps.pony : "src/mqtt-utilities/timestamps.md" 
  - formaters.pony : "src/mqtt-utilities/formaters.md" 
  - fixedHeader.pony : "src/mqtt-utilities/fixedHeader.md" 
  - testPackets.pony : "src/mqtt-utilities/testPackets.md" 